services:
  mysql:
    image: mysql:latest
    container_name: mi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi_contraseña
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mi_usuario", "-pmi_password"]
      interval: 5s
      timeout: 3s
      retries: 10
      
  cargabd:
    build: ./db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./db:/app
    working_dir: /app
    command: ["python", "cargarBD.py"]

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend


volumes:
  mysql_data:
